export const FAILURE = "TASK/FAILURE";
export const LOADING = "TASK/LOADING";

export const SHOW_ALERT = "TASK/SHOW_ALERT";
export const HIDE_ALERT = "TASK/HIDE_ALERT";

export const CREATE_ACCOUNT = "TASK/CREATE_ACCOUNT";
export const LOGIN = "TASK/LOGIN";
export const LOGOUT = "TASK/LOGOUT";

export const CREATE_ARTICLE = "TASK/CREATE_ARTICLE";
export const GET_ARTICLES = "TASK/GET_ARTICLES";
export const GET_ARTICLE = "TASK/GET_ARTICLE";

export const CHANGE_USERNAME = "TASK/CHANGE_USERNAME";
export const CHANGE_PASSWORD = "TASK/CHANGE_PASSWORD";

export const SEND_COMMENT = "TASK/SEND_COMMENT";
